# Generated by Django 5.2 on 2025-05-06 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("is_answered", models.BooleanField(default=False)),
                (
                    "answer",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("YES", "Yes"),
                            ("NO", "No"),
                            ("NA", "N/A"),
                            ("ALT", "Alternate"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="api.assessment",
                    ),
                ),
            ],
        ),
    ]
