# Generated by Django 5.2 on 2025-05-19 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_assessment_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssessmentTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="question",
            name="assessment",
        ),
        migrations.CreateModel(
            name="QuestionTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "assessment_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="api.assessmenttemplate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed", models.BooleanField(default=False)),
                (
                    "assessment_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.assessmenttemplate",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_assessments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answer",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("YES", "Yes"),
                            ("NO", "No"),
                            ("NA", "N/A"),
                            ("ALT", "Alternate"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "question_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.questiontemplate",
                    ),
                ),
                (
                    "user_assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="api.userassessment",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Assessment",
        ),
        migrations.DeleteModel(
            name="Question",
        ),
    ]
