# Generated by Django 5.2 on 2025-05-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_assessmenttemplate_remove_question_assessment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userassessment',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
