# Generated by Django 5.2 on 2025-05-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userassessment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmenttemplate',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
