# Generated by Django 5.2 on 2025-05-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_assessmenttemplate_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questiontemplate",
            name="assessment_template",
        ),
        migrations.AddField(
            model_name="assessmenttemplate",
            name="questions",
            field=models.ManyToManyField(
                related_name="assessment_templates", to="api.questiontemplate"
            ),
        ),
    ]
