# Generated by Django 5.2 on 2025-06-17 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_remove_questiontemplate_assessment_template_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnswerOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=20)),
                ("label", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="AnswerOptionSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="QuestionArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="useranswer",
            name="answer",
        ),
        migrations.AddField(
            model_name="useranswer",
            name="selected_option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.answeroption",
            ),
        ),
        migrations.AddField(
            model_name="answeroption",
            name="option_set",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="api.answeroptionset",
            ),
        ),
        migrations.AddField(
            model_name="questiontemplate",
            name="option_set",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.answeroptionset",
            ),
        ),
        migrations.AddField(
            model_name="questiontemplate",
            name="area",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="questions",
                to="api.questionarea",
            ),
            preserve_default=False,
        ),
    ]
