# Generated by Django 5.2 on 2025-07-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_answeroption_answeroptionset_questionarea_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="useranswer",
            name="marked_for_review",
            field=models.BooleanField(default=False),
        ),
    ]
