# Generated by Django 5.2 on 2025-08-07 08:41

from django.db import migrations


def create_roles(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    roles = ["Admin", "Editor", "Base_User"]
    for role in roles:
        Group.objects.get_or_create(name=role)


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_useranswer_marked_for_review"),
    ]

    operations = [
        migrations.RunPython(create_roles),
    ]
