# Generated by Django 5.2 on 2025-07-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_useranswer_marked_for_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontemplate',
            name='nist_csf',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questiontemplate',
            name='ref',
            field=models.TextField(blank=True, null=True),
        ),
    ]
