# Generated by Django 5.2 on 2025-07-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_questiontemplate_nist_csf_questiontemplate_ref'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questiontemplate',
            old_name='ref',
            new_name='reference',
        ),
        migrations.AddField(
            model_name='questiontemplate',
            name='recomendation',
            field=models.TextField(default='Sin recomendación'),
            preserve_default=False,
        ),
    ]
