# Generated by Django 5.2 on 2025-07-17 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_ref_questiontemplate_reference_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questiontemplate',
            old_name='recomendation',
            new_name='recommendation',
        ),
    ]
