# Generated by Django 5.2 on 2026-05-27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_rename_recomendation_questiontemplate_recommendation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userassessment",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_assessments",
                to="auth.user",
            ),
        ),
        migrations.AddField(
            model_name="userassessment",
            name="user_email_snapshot",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="userassessment",
            name="user_username_snapshot",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.RemoveField(
            model_name="questiontemplate",
            name="nist_csf",
        ),
        migrations.RemoveField(
            model_name="questiontemplate",
            name="reference",
        ),
        migrations.RemoveField(
            model_name="questiontemplate",
            name="recommendation",
        ),
        migrations.CreateModel(
            name="AssessmentAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment_access_requests",
                        to="auth.user",
                    ),
                ),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_requests",
                        to="api.assessmenttemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assessment Access",
                "verbose_name_plural": "Assessment Accesses",
                "unique_together": {("user", "assessment")},
            },
        ),
        migrations.AddIndex(
            model_name="assessmentaccess",
            index=models.Index(fields=["user", "assessment", "status"], name="api_assessm_user_asses_0fb65b_idx"),
        ),
    ]