# Generated by Django 5.2 on 2026-05-29 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_adjust_models_to_requested_schema'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='assessmentaccess',
            new_name='api_assessm_user_id_09bd5b_idx',
            old_name='api_assessm_user_asses_0fb65b_idx',
        ),
    ]
