services:
  backend:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile
    container_name: django_app
    # Para desarrollo
    command: python manage.py runserver 0.0.0.0:8000
    # Para producción
    # command: >
    #      sh -c "python manage.py collectstatic --noinput &&
    #        gunicorn backend.wsgi:application --bind 0.0.0.0:8000 --access-logfile - --error-logfile -"
    volumes:
      - ./backend:/app/backend
    # En desarrollo Django gestiona los ficheros estáticos
    #  - static_volume:/app/staticfiles
    working_dir: /app/backend
    # Comentarlo para producción
    ports:
      - "8001:8000"
    env_file:
      - .env
      - ./backend/.env
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile
    container_name: vite_app
    volumes:
      - ./frontend:/app/frontend
      # Descomentarlo para producción
      # - ./frontend/dist:/app/frontend/dist
    working_dir: /app/frontend
    # Para desarrollo
    command: sh -c "npm install && npm run dev -- --host"
    # Para producción
    # command: sh -c "npm install && npm run build"
    # Comentarlo en producción
    ports:
      - "5173:5173"

  db:
    image: postgres:15
    container_name: postgres_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"

  # nginx:
  #   image: nginx:alpine
  #   container_name: nginx_proxy
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./frontend/dist:/usr/share/nginx/html:ro
  #     - static_volume:/static
  #   depends_on:
  #     - frontend
  #     - backend


volumes:
  pgdata:
    # Descomentarlo en producción
  # static_volume:
  # frontend_build:
